export const popSingers = [
    { id: 1 ,name: 'Drake', gender: 'Male', age: 16, university: 'DIA', education: 'Magistr', department: 'IT' },
    { id: 2 ,name: 'Beyonce', gender: 'Female', age: 32, university: 'UNEC', education: 'Bakalavr', department: 'RM' },
    { id: 3 ,name: 'Rihanna', gender: 'Male', age: 45, university: 'ADU', education: 'Magistr', department: 'LP' },
    { id: 4 ,name: 'Justin Bieber', gender: 'Female', age: 76, university: 'BDU', education: 'Bakalavr', department: 'AF' },
    { id: 5 ,name: 'Koray Avci', gender: 'Female', age: 23, university: 'ATU', education: 'Bakalavr', department: 'HR' },
    { id: 6 ,name: 'Ceza', gender: 'Male', age: 33, university: 'ADA', education: 'Bakalavr', department: 'CE' },
    { id: 7 ,name: 'Ezhel', gender: 'Female', age: 48, university: 'ADA', education: 'Bakalavr', department: 'IT' },
    { id: 8 ,name: 'Emre Aydin', gender: 'Female', age: 54, university: 'BDU', education: 'Bakalavr', department: 'IT' },
    { id: 9 ,name: 'Tarkan', gender: 'Male', age: 82, university: 'DIA', education: 'Bakalavr', department: 'RM' },
    { id: 10 ,name: 'Heyder Aliyev', gender: 'Female', age: 90, university: 'UNEC', education: 'Bakalavr', department: 'HR' },
    { id: 11 ,name: 'Drake', gender: 'Female', age: 16, university: 'DIA', education: 'Bakalavr', department: 'CE' },
    { id: 12 ,name: 'Beyonce', gender: 'Female', age: 32, university: 'DIA', education: 'Magistr', department: 'AF' },
    { id: 13 ,name: 'Rihanna', gender: 'Male', age: 45, university: 'DIA', education: 'Bakalavr', department: 'IT' },
    { id: 14 ,name: 'Justin Bieber', gender: 'Female', age: 76, university: 'BDU', education: 'Bakalavr', department: 'LP' },
    { id: 15 ,name: 'Koray Avci', gender: 'Female', age: 23, university: 'DIA', education: 'Bakalavr', department: 'IT' },
    { id: 16 ,name: 'Ceza', gender: 'Female', age: 33, university: 'ATU', education: 'Bakalavr', department: 'RM' },
    { id: 17 ,name: 'Ezhel', gender: 'Male', age: 48, university: 'UNEC', education: 'Bakalavr', department: 'HR' },
    { id: 18 ,name: 'Emre Aydin', gender: 'Female', age: 54, university: 'BDU', education: 'Bakalavr', department: 'LP' },
    { id: 19 ,name: 'Tarkan', gender: 'Male', age: 82, university: 'DIA', education: 'Magistr', department: 'CE' },
    { id: 20 ,name: 'Heyder Aliyev', gender: 'Male', age: 90, university: 'ATU', education: 'Bakalavr', department: 'CE' },
];
